services:
  api:
    image: ghcr.io/phylip28/task-manager:main
    
    container_name: tm-api

    env_file:
      - .env
    
    ports:
      - "127.0.0.1:8000:8000"

    depends_on:
      - db

  db:
    image: postgres:15-alpine

    container_name: tm-db

    volumes:
      - "postgres_data:/var/lib/postgresql/data"

    env_file:
      - .env

volumes:
  postgres_data: